function cat_buildall()

%   CAT_BUILDALL -- Build all mex functions.

cat_build( {...
      'cat_api.cpp' ...
    , 'cat_mex_helpers.cpp' ...
    , 'cat_getlabs.cpp' ...
    , 'cat_getcats.cpp' ...
    , 'cat_create.cpp' ...
    , 'cat_destroy.cpp' ...
    , 'cat_setcat.cpp' ...
    , 'cat_requirecat.cpp' ...
    , 'cat_findallc.cpp' ...
    , 'cat_findall.cpp' ...
    , 'cat_size.cpp' ...
    , 'cat_append.cpp' ...
    , 'cat_find.cpp' ...
    , 'cat_fullcat.cpp' ...
    , 'cat_incat.cpp' ...
    , 'cat_keep.cpp' ...
    , 'cat_setpartcat.cpp' ...
    , 'cat_copy.cpp' ...
    , 'cat_resize.cpp' ...
    , 'cat_haslab.cpp' ...
    , 'cat_hascat.cpp' ...
    , 'cat_isvalid.cpp' ...
    , 'cat_fillcat.cpp' ...
    , 'cat_repeat.cpp' ...
    , 'cat_keepeach.cpp' ...
    , 'cat_keepeachc.cpp' ...
    , 'cat_collapsecat.cpp' ...
    , 'cat_one.cpp' ...
    , 'cat_equals.cpp' ...
    , 'cat_partcat.cpp' ...
    , 'cat_rmcat.cpp' ...
    , 'cat_ncats.cpp' ...
    , 'cat_nlabs.cpp' ...
    , 'cat_assign.cpp' ...
    , 'cat_setcats.cpp' ...
    , 'cat_setpartcats.cpp' ...
    , 'cat_assignpart.cpp' ...
    , 'cat_prune.cpp' ...
    , 'cat_count.cpp' ...
    , 'cat_numcats.cpp' ...
    , 'cat_buildconfig.cpp' ...
    , 'cat_empty.cpp' ...
    , 'cat_progenitorsmatch.cpp' ...
}, 'src' );

end